### ISSUE TITLE
Use environment in type checking

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#111]
Pass a variable binding to the type checking that maps variable names to security labels `L` and `H`. Use these bindings instead of annotations in the AST.

**Comment by jan-christiansen** [comment]
Please pass the environment as an argument to `security`.

**Comment by MadeInGer** [comment]
I just want to mention that I did some little changes with the last commit in the security checker:
- changed ast-Kind 'Do' to 'Body', which was a left over from earlier versions of the codegenerator
- added Null-Kind, since it has been newly introduces in the codegenerator
- replaced the examples in main() with a current example
