### ISSUE TITLE
Read papers of vector representations

### ISSUE THREAD

**Issue by DanielEggelmann** [sagr4019/ResearchProject#123]
Read the following papers:
- [A General Path-Based Representation for Predicting Program Properties](https://arxiv.org/pdf/1803.09544.pdf)
- [code2seq: Generating Sequences from Structured Representations of Code](https://arxiv.org/pdf/1808.01400.pdf)

**Comment by Zermy** [comment]
Answer the questions:

- Clarify arrow representations ?
- Limiting of the paths ?
- What type of network is used ?
- Applicability to our questions ?
- What was published ?

**Comment by jan-christiansen** [comment]
In order to preserve this information, here are some links to published source code related to the three publications (the third is [code2vec: Learning Distributed Representations of Code](https://arxiv.org/pdf/1803.09473.pdf)).

- https://github.com/urialon?tab=repositories
- https://github.com/tech-srl
- https://code2vec.org
