### ISSUE TITLE
Develop a concept for converting AST into vectors

### ISSUE THREAD

**Issue by Zermy** [sagr4019/ResearchProject#126]
Think of a variant to get from AST into a form of representation from which you can later transform to vectors.

**Comment by Zermy** [comment]
@sagr4019 [Tokens](https://blog.klipse.tech/javascript/2017/02/08/tiny-compiler-parser.htm)l What do you think?

**Comment by jan-christiansen** [comment]
Please use an approach or a combination of approaches that we have read about.

**Comment by sagr4019** [comment]
Concept:

In order to make Vectors of our AST object we suggest parsing every node that is helpful: (- assign -declaration)? for our classification task into a vector with word2vec/seq2vec
For Example we modify the ast and delete unnecessary nodes, use the pretty printer to make sequences and make use of seq2vec f.e. from here: https://github.com/Yoctol/seq2vec and convert 
it to a vector representation

https://arxiv.org/pdf/1710.06159.pdf

**Comment by Zermy** [comment]
The approach has already been found. We use the approach from 
[paper](https://bdqnghi.github.io/files/AAAI_18_cross_language_learning.pdf). The adjustments from our AST structure to this is in progress and close to completion.
