### ISSUE TITLE
Train net with long programs only

### ISSUE THREAD

**Issue by jan-christiansen** [sagr4019/ResearchProject#149]
Is the net able to generalise the behaviour for short programs, if we train it with long programs only? Train the net with programs that are near the maximal number of tokens. Save the resulting weights into the `models` folder. Please try to improve the naming scheme of the files with pertained weights.

**Comment by DanielEggelmann** [comment]
#155 The issue that the network does not classify the crafted examples correctly, seems to be a problem with LSTM networks. Over time (elements of the sequence) LSTM networks seem to forget the crucial information needed to identify the type of program (security class of variables). This could be due to each neuron in a LSTM layer adds and removes information from the memorized information, therefore distorting them.
Another issue why training with long programs might not improve the detection, is that while the programs themselves might be near maximum size, there is no way to guarantee that the instruction which invalidate the program are also near the end of the program.
