### ISSUE TITLE
Overfitting

### ISSUE THREAD

**Issue by Zermy** [sagr4019/ResearchProject#4]
How "Learning a Static Analyzer from Data (https://arxiv.org/pdf/1611.01752.pdf)" solve overfitting?

**Comment by MadeInGer** [comment]
What is overfitting?
We call it overfitting if the model works great with the training data, but poor with test data. The  algorithm is probably bad at generalization, because noise and other fluctuations in the training data has been learned as concepts and these concepts are good for the training data, but on the other hand not suitable for test data, because the features are missing.
E. g. if we put training data containing images of white cats into our system to make the model learning based on those images, the model will probably fail to detect black cats in the test data due to the limitation on white cats.
The matching counterpart to overfitting is called underfitting and is given once the model isn’t suitable for both training data as well as the test data.
Both mentioned problems lead to poor performance referring to the model. To get rid of over- and underfitting the training data with the features has to be selected wisely. If we want to analyze data to find rules, e. g. to get the most used character in a language, the training data set has to be big - it is not useful to choose just one sentence to analyze a language in terms of the frequency of chars. 
Overstated cycles of the training set could end up in overfitting. Firstly the results seems to be good and the amount of correct results increases once we use test data. But the amount of correct results on the test data set decreases after some time, because too many concepts has been generated from the training data that doesn’t fit to the test data.
A way to avoid overfitting is called regularization (different issue).

**Comment by jan-christiansen** [comment]
Please add a short text about overfitting to the wiki.

**Comment by MadeInGer** [comment]
An entry has been created and is available at https://github.com/sagr4019/ResearchProject/wiki/Overfitting.

**Comment by jan-christiansen** [comment]
* Please remove `pruning` or extend it. As it is specific to decision trees it might be wrong in this article anyway
* What does the term coefficients mean in the following sentence "the penalty has the most impact for high regression coefficients or if there are many coefficients that are not null.". Is this statement specific to neural networks?

**Comment by MadeInGer** [comment]
The wiki article has been updated. I couldn't find any information related to the coefficients that explains the meaning in more detail, so it has been removed. Maybe it will be clearer during our next weeks of researching.
